### ISSUE TITLE
2021-12- 2 Peer-to-peer code review

### ISSUE THREAD

**Issue by ShadyShawkat** [vechicin/To-Do-List#2]
# Hi @vechicin, 👋🏻 

I really liked your project. I especially liked how you organized your code to be very readable and easy to understand with comments for every section. 👍🏻 

# Here are some suggestions...

- You could add the 'Clear all completed' button outside of the `ul` and style it with the appropriate styles. That will make more sense since every time the list is updated you won't have to rerender the button and add the event listener to it.

- You can add the 'line through' style for the completed todos as a class in your CSS and then add it through your js every time the checkbox is checked. This opens up the possibilities of adding more styles to the completed todos like changing the color of the text and so on, it could also help you in the long run to select the completed tasks through this class.

**Once again, I really liked your project and how well organized it is. Keep up the good work.**  😄 🚀

**Comment by gdumani** [comment]
Nice project!!!

- Good use of class names as pointers for events
- Don’t forget to eliminate the unused code
